# Generated by Django 5.2 on 2025-04-30 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0002_rename_kategogi_kategori'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kategori',
            table='artikel_kategori',
        ),
    ]
