# Generated by Django 5.2 on 2025-04-30 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0003_alter_kategori_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
