# Generated by Django 5.2 on 2025-04-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0004_alter_kategori_nama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kategori',
            name='nama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
