# Generated by Django 5.2 on 2025-06-25 17:27

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artikel', '0005_alter_kategori_nama'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artikelblog',
            options={'verbose_name_plural': '2. Artikel Blogs'},
        ),
        migrations.AlterModelOptions(
            name='kategori',
            options={'verbose_name_plural': '1. Kategori'},
        ),
        migrations.AlterField(
            model_name='artikelblog',
            name='konten',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Text'),
        ),
        migrations.AlterModelTable(
            name='kategori',
            table=None,
        ),
    ]
